export function escapeHtml(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;')
}
export function issueShareHtml(input: { title: string; summary: string; bodyName: string; placeName: string; mode: 'full' | 'limited'; canonicalUrl: string; shareUrl: string }): string {
  const title = escapeHtml(`${input.title} | Public Parish`)
  const summary = escapeHtml(input.summary)
  const canonical = escapeHtml(input.canonicalUrl)
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${summary}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="article"><meta property="og:site_name" content="Public Parish"><meta property="og:title" content="${title}"><meta property="og:description" content="${summary}"><meta property="og:url" content="${escapeHtml(input.shareUrl)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${summary}"><style>body{margin:0;background:#fafaf9;color:#202622;font:18px/1.6 system-ui,sans-serif}main{max-width:46rem;margin:8vh auto;padding:2rem}h1{font-size:clamp(2rem,5vw,3.3rem);line-height:1.15;letter-spacing:-.04em}a{color:#155e42}header{border-bottom:1px solid #d6ddd7;padding-bottom:1rem}.status{font-size:.9rem}.action{display:inline-block;margin-top:1rem;padding:.7rem 1rem;background:#155e42;color:white;border-radius:.4rem}footer{margin-top:3rem;font-size:.9rem}</style></head><body><main><header><a href="/">Public Parish</a><p>${escapeHtml(input.placeName)} · ${escapeHtml(input.bodyName)}</p></header><h1>${escapeHtml(input.title)}</h1><p class="status">${input.mode === 'limited' ? 'Limited information. Some details remain unpublished.' : 'Published from validated official evidence.'}</p><p>${summary}</p><a class="action" href="${canonical}">Read the timeline and official sources</a><footer>Free, open-source, nonpartisan Louisiana civic information. <a href="/coverage">See supported bodies and limitations</a>.</footer></main></body></html>`
}
